### ISSUE TITLE
The accuracy of model SMA

### ISSUE THREAD

**Issue by 10652835** [JayZhu0104/Introduction-About-TextVQA#1]
In the paper,the accuracy of model SMA on test dataset is 40.66,Did you make a mistake?

**Comment by JayZhu0104** [comment]
Yes, the accuracy in the paper is 40.66 and the accuracy in the TextVQA 2020 challenge is 45.61.
Ref: https://evalai.cloudcv.org/web/challenges/challenge-page/551/leaderboard/1575#leaderboardrank-3

**Comment by 10652835** [comment]
Thank you for your reply
